// Code generated by xgo (XGo); DO NOT EDIT.

package utils

import "fmt"

const _ = true
//line cpkag/utils/csgo.gop:5:1
func TestCsgo() {
//line cpkag/utils/csgo.gop:6:1
	fmt.Println("my testcsgo")
}
