// Code generated by xgo (XGo); DO NOT EDIT.

package k

import "fmt"

const _ = true
//line cpkag/k/k.gop:3:1
func Kk() {
//line cpkag/k/k.gop:4:1
	fmt.Println("kk")
}
//line cpkag/k/k.gop:7:1
func Ab() {
//line cpkag/k/k.gop:8:1
	fmt.Println("ab")
}
