// Code generated by xgo (XGo); DO NOT EDIT.

package ss

import "fmt"

const _ = true
//line cpkag/b/ss/b.gop:3:1
func Bs() {
//line cpkag/b/ss/b.gop:4:1
	fmt.Println("bs")
}
//line cpkag/b/ss/ss.gop:3:1
func Ab() {
//line cpkag/b/ss/ss.gop:4:1
	fmt.Println("ab")
}
